name: Main

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-fe:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build front
        run: |
          cd client
          yarn
          npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: fe-build
          path: client/build
          retention-days: 1

  deploy-fe:
    needs: build-fe
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: fe-build
          path: build

      - name: Upload artifact to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'build'
          target: '~/fe-build'

  deploy-be:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Pack
        run: |
          cd ..
          tar --exclude="build" --exclude="client" --exclude=".git" --exclude="node_modules" -zcvf backend.tar.gz memo-nft/
          mv backend.tar.gz memo-nft/

      - name: Upload codebase to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'backend.tar.gz'
          target: 'app'

      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd app
            tar -xvzf backend.tar.gz 
            cd memo-nft
            npm i

  deploy-all:
    needs: [deploy-fe, deploy-be]
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - name: Move front to host folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mv fe-build/build app/memo-nft/
            sudo service NftMemo stop
            sudo service NftMemo start
            sudo service NftMemo status
